[supervisord]
nodaemon=true
loglevel=info ; Define o nível de log do Supervisor
user=root      ; Define o usuário sob o qual o Supervisor será executado (pode ser outro usuário se desejar)
logfile=/var/log/supervisor/supervisord.log ; Arquivo de log do próprio Supervisor
pidfile=/var/run/supervisord.pid             ; Arquivo PID do Supervisor
childlogdir=/var/log/supervisor              ; Diretório para logs dos processos gerenciados

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
stdout_logfile=/dev/stdout    ; Redireciona a saída padrão do Nginx para os logs do Docker
stdout_logfile_maxbytes=0     ; Desabilita o limite de tamanho do arquivo de log
stderr_logfile=/dev/stderr    ; Redireciona a saída de erro do Nginx para os logs do Docker
stderr_logfile_maxbytes=0     ; Desabilita o limite de tamanho do arquivo de log
autostart=true
autorestart=true
priority=10

[program:php-fpm]
command=php-fpm -F
stdout_logfile=/dev/stdout    ; Redireciona a saída padrão do PHP-FPM para os logs do Docker
stdout_logfile_maxbytes=0     ; Desabilita o limite de tamanho do arquivo de log
stderr_logfile=/dev/stderr    ; Redireciona a saída de erro do PHP-FPM para os logs do Docker
stderr_logfile_maxbytes=0     ; Desabilita o limite de tamanho do arquivo de log
autostart=true
autorestart=true
priority=20